Comment : update a bunch of stuff on Mon 4 Jun 18 at 01:32

diff --git a/bin/bin/freshcoat b/bin/bin/freshcoat
--- a/bin/bin/freshcoat
+++ b/bin/bin/freshcoat
@@ -1,196 +1,208 @@
 #!/usr/bin/env bash
 
-# ARGS
+# Grab options from config folder & use fzf to filter/find and select
 COLORSCHEME="$(ls /home/daniel/.config/freshcoat | sort --reverse | fzf --cycle)"
 
-# CACHE & THEME DIRS
+# Cache & theme dirs
 CACHEDIR=$HOME/.cache/freshcoat
 THEMEDIR=$HOME/.config/freshcoat
 WM=$(head -n 1 $CACHEDIR/wm)
 THEME=$COLORSCHEME
+RGBABG=$(colorconvert "$(xrq '*.background' | awk -F\] '{print $2}')" | sed 's/)/, 0\.9)/g;s/rgb/rgba/g')
 
-# SEQUENCE DEF 
+# Define sequence and newline helper
 NL=$'\n'
 sequence=""
 
-# CLEANUP CACHE FILES
+# Cleanup cache files
 cleanup() {
-	rm -f $CACHEDIR/x_colors
+    rm -f $CACHEDIR/x_colors
 }
 
-# RELOAD TERMINAL
+# Reload terminals
 reloadx() {
-	for term in /dev/pts/[0-9]*; do
-		printf "%b" "$sequence" > "$term"
-	done
+    for term in /dev/pts/[0-9]*; do
+        printf "%b" "$sequence" > "$term"
+    done
 }
 
 mergex() {
-	xrdb -merge ${HOME}/.Xresources
+    xrdb -merge ${HOME}/.Xresources
 }
 
-# RELOAD LEMONBAR
+# Reload lemonbar
 reload_bar() {
-	pkill -x lemonbar
-	lpanel &
+    pkill -x lemonbar
+    lpanel &
 }
 
-# BUILD COLOR ARRAY
+# Build color array
 get_colors() {
-	. $THEMEDIR/$THEME
-	COLOR_ARRAY=($blk $red $grn $ylw $blu $mag $cyn $wht \
-				 $bblk $bred $bgrn $bylw $bblu $bmag $bcyn $bwht)
+    . $THEMEDIR/$THEME
+    COLOR_ARRAY=($blk $red $grn $ylw $blu $mag $cyn $wht \
+	        $bblk $bred $bgrn $bylw $bblu $bmag $bcyn $bwht)
 }
 
-# ADD COLORS TO SEQUENCE
+# Add colors to sequence
 create_sequence() {
-	for i in {0..15}
-	do
-		sequence+="\033]4;${i};${COLOR_ARRAY[${i}]}\007"
-	done
+    for i in {0..15}; do
+	sequence+="\033]4;${i};${COLOR_ARRAY[${i}]}\007"
+    done
 }
 
-# ADD BG & FG COLORS TO SEQUENCE FROM SOURCED VARS
+# Add BG & FG colors to sequence from sourced vars
 create_second_sequence() {
-	# FG
-	for i in 10 12 13; do
-		sequence+="\033]${i};${fg}\007"
-	done
+# FG
+    for i in 10 12 13; do
+	sequence+="\033]${i};${fg}\007"
+    done
+# BG
+    for i in 11 14 708; do
+	sequence+="\033]${i};${bg}\007"
+    done
+}
 
-	# BG
-	for i in 11 14 708; do
-		sequence+="\033]${i};${bg}\007"
-	done
+write_termite() {
+    termite_output+="color0 = ${blk}${NL}"
+    termite_output+="color1 = ${red}${NL}"
+    termite_output+="color2 = ${grn}${NL}"
+    termite_output+="color3 = ${ylw}${NL}"
+    termite_output+="color4 = ${blu}${NL}"
+    termite_output+="color5 = ${mag}${NL}"
+    termite_output+="color6 = ${cyn}${NL}"
+    termite_output+="color7 = ${wht}${NL}"
+    termite_output+="color8 = ${bblk}${NL}"
+    termite_output+="color9 = ${bred}${NL}"
+    termite_output+="color10 = ${bgrn}${NL}"
+    termite_output+="color11 = ${bylw}${NL}"
+    termite_output+="color12 = ${bblu}${NL}"
+    termite_output+="color13 = ${bmag}${NL}"
+    termite_output+="color14 = ${bcyn}${NL}"
+    termite_output+="color15 = ${bwht}${NL}"
+    termite_output+="foreground = ${fg}${NL}"
+    termite_output+="background = ${bg}${NL}"
+    termite_output+="cursor = ${fg}${NL}"
+
+    sed -i '20,38d' ~/.config/termite/config
+    printf "${termite_output}" >> "/home/daniel/.config/termite/config"
 }
 
 write_x_source() {
-	x_output=""
-	x_output+="*.foreground:  ${fg}${NL}"
-	x_output+="*.background:  [95]${bg}${NL}"
-	x_output+="*.cursorColor: ${fg}${NL}"
+    x_output=""
+    x_output+="*.foreground:  ${fg}${NL}"
+    x_output+="*.background:  ${bg}${NL}"
+    x_output+="URxvt.background:  [95]${bg}${NL}"
+    x_output+="*.cursorColor: ${fg}${NL}"
 
-	for i in {0..15}; do
-		x_output+="*.color${i}: ${COLOR_ARRAY[${i}]}${NL}"
-	done
+    for i in {0..15}; do
+	x_output+="*.color${i}: ${COLOR_ARRAY[${i}]}${NL}"
+    done
 }
 
 write_rofi() {
-	rofi_output=""
-	rofi_output+="rofi.color-enabled: true${NL}"
-	rofi_output+="rofi.color-window: ${bg}, ${bg}, ${blk}${NL}"
-	rofi_output+="rofi.color-normal: ${bg}, ${fg}, ${bg}, ${blk}, ${cyn}${NL}"
+    rofi_output=""
+    rofi_output+="rofi.color-enabled: true${NL}"
+    rofi_output+="rofi.color-window: ${bg}, ${bg}, ${blk}${NL}"
+    rofi_output+="rofi.color-normal: ${bg}, ${fg}, ${bg}, ${blk}, ${cyn}${NL}"
 }
 
-# SH COLORS
+# SH Colors
 write_sh() {
-	rm -f $CACHEDIR/colors 
-	cp $THEMEDIR/$THEME $CACHEDIR/colors
+    rm -f $CACHEDIR/colors 
+    cp $THEMEDIR/$THEME $CACHEDIR/colors
 }
 
-# WRITE OUTPUT TO x_colors in $CACHEDIR
+# Write output to x_colors in $CACHEDIR
 write_all() {
-	output=${x_output}${rofi_output}
-	printf "${output}" > "${CACHEDIR}/x_colors"
+    output=${x_output}${rofi_output}
+    printf "${output}" > "${CACHEDIR}/x_colors"
 }
 
 write_x_define() {
-	xd_output=""
-	xd_output+="#define bg  ${bg}${NL}"
-	xd_output+="#define blk  ${blk}${NL}"
-	xd_output+="#define bblk  ${bblk}${NL}"
-	xd_output+="#define fg  ${fg}${NL}"
-	xd_output+="#define red  ${red}${NL}"
-	xd_output+="#define bred  ${bred}${NL}"
-	xd_output+="#define grn  ${grn}${NL}"
-	xd_output+="#define bgrn  ${bgrn}${NL}"
-	xd_output+="#define ylw  ${ylw}${NL}"
-	xd_output+="#define bylw  ${bylw}${NL}"
-	xd_output+="#define blu  ${blu}${NL}"
-	xd_output+="#define bblu  ${bblu}${NL}"
-	xd_output+="#define mag  ${mag}${NL}"
-	xd_output+="#define bmag  ${bmag}${NL}"
-	xd_output+="#define cyn  ${cyn}${NL}"
-	xd_output+="#define bcyn  ${bcyn}${NL}"
-	xd_output+="#define wht  ${wht}${NL}"
-	xd_output+="#define bwht  ${bwht}${NL}"
+    xd_output=""
+    xd_output+="#define bg  ${bg}${NL}"
+    xd_output+="#define blk  ${blk}${NL}"
+    xd_output+="#define bblk  ${bblk}${NL}"
+    xd_output+="#define fg  ${fg}${NL}"
+    xd_output+="#define red  ${red}${NL}"
+    xd_output+="#define bred  ${bred}${NL}"
+    xd_output+="#define grn  ${grn}${NL}"
+    xd_output+="#define bgrn  ${bgrn}${NL}"
+    xd_output+="#define ylw  ${ylw}${NL}"
+    xd_output+="#define bylw  ${bylw}${NL}"
+    xd_output+="#define blu  ${blu}${NL}"
+    xd_output+="#define bblu  ${bblu}${NL}"
+    xd_output+="#define mag  ${mag}${NL}"
+    xd_output+="#define bmag  ${bmag}${NL}"
+    xd_output+="#define cyn  ${cyn}${NL}"
+    xd_output+="#define bcyn  ${bcyn}${NL}"
+    xd_output+="#define wht  ${wht}${NL}"
+    xd_output+="#define bwht  ${bwht}${NL}"
 
-	printf "${xd_output}" > "$CACHEDIR/xd_colors"
+    printf "${xd_output}" > "$CACHEDIR/xd_colors"
 }
 
 write_name() {
-        name_output="$THEME"
-
-        printf "${name_output}" > "$CACHEDIR/current"
+    name_output="$THEME"
+    printf "${name_output}" > "$CACHEDIR/current"
 }
 
 setwall() {
-	. ~/.fehbg &
+    . ~/.fehbg &
 }
 
 obcolor() {
-if ! pgrep -x "bspwm" > /dev/null ;
-then
-    obsquash &
-fi
+    if ! pgrep -x "bspwm" > /dev/null ; then
+        obsquash &
+    fi
 }
 
 hcreload() {
-if ! pgrep -x "bspwm" > /dev/null ;
-then    
-    exec herbstclient reload &
-fi
+    if ! pgrep -x "bspwm" > /dev/null ; then
+        exec herbstclient reload &
+    fi
 }
-    
 
 bspfresh() {
-if  ! pgrep -x "openbox" > /dev/null ; 
-then
-    ~/.config/bspwm/bspwmrc &
-fi
+    if  ! pgrep -x "openbox" > /dev/null ; then
+        ~/.config/bspwm/bspwmrc &
+    fi
 }
-
-
-
 
 roficolor() {
-	exec $HOME/bin/rofisquash &
+    exec $HOME/bin/rofisquash &
 }
+
 {
 if [ -f $THEMEDIR/$COLORSCHEME ]; then
-	# CLEANUP
-	cleanup
 
-	# SOURCE COLORS
-	get_colors
-
-	# CREATE TERMINAL RELOAD SEQUENCE
-	create_sequence
-	create_second_sequence
-
-	# RELOAD THEM SHITS
-	reloadx
-
-	# WRITE COLORS TO CACHE
-	write_x_source
-	write_rofi
-	write_all
-	write_sh
-	write_x_define
-        write_name
-
-	# MERGE X
-	mergex
-	reload_bar
-	roficolor
-	obcolor
-        bspfresh
-        hcreload
-	#setwall
+# Cleanup
+    cleanup
+# Source colors
+    get_colors
+# Create terminal reload sequence
+    create_sequence
+    create_second_sequence
+# Reload the fucking thing
+    reloadx
+# Write theme to cache
+    write_x_source
+    write_termite
+    write_rofi
+    write_all
+    write_sh
+    write_x_define
+    write_name
+# Merge X
+    mergex
+    reload_bar
+    roficolor
+    obcolor
+    bspfresh
+    hcreload
+    #setwall
 
 else
-	printf "YOU DID IT WRONG"
+    printf "You're doing it wrong."
 fi
 } 2> /dev/null
-#{
- #fresh 
- #} 2> /dev/null 
